### ISSUE TITLE
Modded workers without an Ideoligion cannot craft/construct

### ISSUE THREAD

**Issue by cabmoomoo** [ZreXoc/RimMod-Im_Proud_of_it#1]
Modded workers that do not belong to Ideoligions, such as those added by [Misc. Robots++](https://steamcommunity.com/sharedfiles/filedetails/?id=3253308913), are fully incompatible with this mod. I believe the culprit to be in this line of code.
https://github.com/ZreXoc/RimMod-Im_Proud_of_it/blob/8728a33caed8f183052aadcf1fe150c8e1c8f9d3/Im_Proud_of_it/Source/ImpCore.cs#L88
Below is a partial debug log provided by another user which has led me to this point:
```
JobDriver threw exception in toil FinishRecipeAndStartStoringProduct's initAction for pawn Crafter Bot (Tier 2) 1 driver=JobDriver_DoBill (toilIndex=17) driver.job=(DoBill (Job_1877253) A = Thing_TableMachining93181 B = Thing_UnfinishedGun372427 C = (144, 0, 160) Giver = JobGiver_Work [workGiverDef: DoBillsMachiningTable])
System.NullReferenceException: Object reference not set to an instance of an object
[Ref 15D21A8]
at ImP.ImpCore.GetRoleEffectQualityOffset (Verse.Pawn worker) [0x00007] in <d2367ec190634db0bac6793f3c680077>:0
at ImP.ImpCore.GetFixedThoughtDefOf (Verse.Pawn worker, Verse.RecipeDef recipeDef, Verse.Thing thing) [0x00039] in <d2367ec190634db0bac6793f3c680077>:0
at ImP.PatchMakeRecipeProducts+<Postfix>d__0.MoveNext () [0x00059] in <d2367ec190634db0bac6793f3c680077>:0
```
Perhaps a quick check to verify the Worker has an Ideoligion is in order? Something to the effect of:
```
private static int GetRoleEffectQualityOffset(Pawn worker)
    {
        if (worker.Ideo == null) {
                return 0
        }
        Precept_Role role = worker.Ideo.GetRole(worker);
...
```
I'm not set up to compile C# projects, so I cannot verify if this is even valid code, let alone if it actually solves the problem. Hopefully it helps, anyway.

Thank you for your time.

**Comment by ZreXoc** [comment]
I guess you're right, and I fixed it just now. Please update the mod and try it. Thank you for your detailed analysis of the bug :)

**Comment by cabmoomoo** [comment]
Bots can craft things with no issues, and a level 4 crafting colonist feels a little pride when making a good revolver. Seems like we're good to go.
